View pokemon
KennethDelaCruz/ajax-project pull request #6
Opened 2021-02-24 08:52 UTC by KennethDelaCruz

2021-02-24 23:13 UTC, KennethDelaCruz commented
![Uploading ajax-project.gif…]()

2021-02-24 23:16 UTC, KennethDelaCruz commented
![ajax-project](https://user-images.githubusercontent.com/69921839/109079080-409a2700-76b3-11eb-8b58-a950f4ff291a.gif)

2021-02-24 23:31 UTC, codingcodymiller requested changes
Hey dude! Yur input and button are off-center when viewed on mobile, please revise 👍

2021-02-24 23:54 UTC, KennethDelaCruz commented
![ajax-project](https://user-images.githubusercontent.com/69921839/109082290-860d2300-76b8-11eb-8792-f35027ffdeb6.gif)

2021-02-24 23:58 UTC, codingcodymiller requested changes

2021-02-24 23:58 UTC, codingcodymiller commented on js/main.js
> +}
Is this being used for anything?

2021-02-25 00:09 UTC, codingcodymiller approved these changes

2021-02-25 00:13 UTC, merged